# Dockerfile.backend

FROM node:18-alpine

WORKDIR /app

# Salin package.json dan package-lock.json untuk menginstal dependensi
COPY package*.json ./

# Instal dependensi (express dan ws)
RUN npm install express ws

# Salin semua file kode aplikasi
COPY . .

# Exposure port yang digunakan oleh server Node.js (internal)
EXPOSE 8080

# Perintah untuk menjalankan aplikasi ketika container dimulai
CMD ["node", "server.js"]