version: '3.8'

services:
  # Service untuk backend Node.js signaling server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # Port 8080 dari backend hanya perlu diakses secara internal oleh Nginx,
    # jadi tidak perlu dipublikasikan langsung ke host (`ports` tidak perlu di sini)
    restart: always

  # Service untuk frontend Nginx yang menyajikan file statis dan proxy WSS
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # Coolify akan secara otomatis memetakan port 80/443 dari container ini
    # ke port 80/443 di host saat Anda menambahkan domain di dashboard Coolify.
    # Tidak perlu "ports: - "80:80"" atau "- "443:443"" di sini.
    depends_on:
      - backend # Pastikan backend berjalan sebelum frontend
    restart: always