# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      # Map port 80 (HTTP) atau 443 (HTTPS) dari container ke host
      # Sesuaikan dengan port yang digunakan di server.js
      - "80:80"  # Untuk HTTP
      # - "443:443" # Untuk HTTPS, uncomment ini dan komen baris di atas
    restart: always
    # UNCOMMENT BAGIAN INI UNTUK HTTPS/WSS:
    # environment:
    #   - PORT=443 # Biarkan server.js mendengarkan di 443
    #   - SSL_KEY_PATH=/app/certs/privkey.pem
    #   - SSL_CERT_PATH=/app/certs/fullchain.pem
    # volumes:
    #   # Mount folder sertifikat SSL dari host ke dalam container
    #   # Lokasi ini harus sesuai dengan yang diakses oleh server.js
    #   # Anda harus memastikan sertifikat ini ada di host Anda
    #   - /etc/letsencrypt/live/yourdomain.com:/app/certs:ro
    #   - /etc/letsencrypt/archive/yourdomain.com:/app/certs-archive:ro # Opsional untuk archive