# Dockerfile.backend
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install express ws
COPY . . # Salin semua kode, termasuk public/
EXPOSE 80 # Atau EXPOSE 443 jika Anda menjalankan HTTPS
CMD ["node", "server.js"]